services:
    kafka:
        image: apache/kafka:3.8.1
        ports:
            - "9092:9092"
        expose:
            - "9092"
    data_producer: # TODO: Only start after kafka is ready to accept connections
        image: data_producer
        depends_on:
            - kafka
        build:
            context: data_producer
            dockerfile: Dockerfile
        volumes:
            - ./data:/data
