version: '3'
services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=trading_data
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin_password
      - INFLUXDB_ORG=my_org
      - INFLUXDB_BUCKET=my_bucket
      - INFLUXDB_INIT_MODE=setup
      - INFLUXDB_INIT_USERNAME=admin
      - INFLUXDB_INIT_PASSWORD=admin_password
      - INFLUXDB_INIT_ORG=my_org
      - INFLUXDB_INIT_BUCKET=my_bucket
    volumes:
      - influxdb-data:/var/lib/influxdb2

volumes:
  influxdb-data:

